version: '3'

volumes:
  pgdatasource:

services:
  capstone-db:
    image: postgres
    restart: always
    container_name: capstone-db
    environment:
     - DATABASE_HOST=127.0.0.1
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_PORT=5432
     - POSTGRES_DB=capstone
    ports:
     - '5432:5432'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  capstone-api:
    build: api/
    container_name: capstone-api
    depends_on:
      capstone-db:
        condition: service_healthy
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - AUTH_URL=http://localhost:8080
      - KEYCLOAK_CLIENT_ID=trojn-api
      - KEYCLOAK_SECRET=X09FGhjLsDYa0DnLAgm39dF4mDwvmHIoLmohUtqzDCIN6VFuAoDBQGlWuRddwnO1lcnmHhOk1N1fqLRcweHVfEW5VS8fKbDK3IoEowvJEFj8nv8bS1dRxEyGmP7JL7A1
      - REALM_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiALpVtuJ3l0FUpem8PHeBI2zQKpd/MbplTFXdMPFuRjKXSnbQ///tukHC0CW0xWkof3ZJ+3CQ98GX2GxpoBTEJMNf543b5o8Af7HFHIZVwc/fUweCGy0cYYjKqZNLq+kGA7MMmorZwMzCTvtvFeMt6IDqf+ZSd8SleqgBpfljAAYX1XPqgr4gGFIm6oTlb9xJrSgcgU6CB9TpnnjUE8gl89Oga2qAtguPznIWr61dat2s9kcc+IUMnYA/lo0Cg5QvSPxaWuJ9oUcbaT3fzFT3mSEechv4CfKaXHlNCPwRU6fHfS4L8oR5flwNrQt1ROCUJ24+79qIcofWlleBbnKcwIDAQAB
      - DATABASE_HOST=capstone-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=capstone
    volumes:
      - type: bind
        source: ./api
        target: /app
    command: npm run start:dev

  capstone-ui:
    build: ui/
    container_name: capstone-ui
    depends_on:
      - 'capstone-api'
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./ui/src
        target: /app/src
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3001
      - REACT_APP_AUTH_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM=showcase-auth
      - REACT_APP_KEYCLOAK_CLIENT=trojn-app